/**
 * generate_maestro_flow — pure YAML builder plus the tool's selector gate. A flow generated by this tool passed live
 * on 2026-10-09 (ExperiBank login, test run 27971411); these tests pin the output shape and the guards.
 */
import { describe, it, beforeAll, afterAll } from 'vitest';
import assert from 'node:assert/strict';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import AdmZip from 'adm-zip';
import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { Client } from '@modelcontextprotocol/sdk/client/index.js';
import { InMemoryTransport } from '@modelcontextprotocol/sdk/inMemory.js';
import { resetClient } from '../src/api/client.js';
import { registerTestRunTools } from '../src/tools/test-run-tools.js';
import { checkMaestroBundle } from '../src/api/test-runs.js';
import { buildMaestroFlowYaml, validateMaestroFlow, bareIdWarnings, flowFileName, type MaestroStep } from '../src/utils/maestro-flow.js';

const APP = 'com.experitest.ExperiBank';
const ID = `${APP}:id/`;
const LOGIN: MaestroStep[] = [
  { action: 'launchApp', clearState: true },
  { action: 'inputText', id: `${ID}usernameTextField`, text: 'company' },
  { action: 'hideKeyboard' },
  { action: 'tapOn', id: `${ID}loginButton` },
  { action: 'assertVisible', text: 'Make Payment' },
  { action: 'scrollUntilVisible', id: `${ID}logoutButton` },
];

describe('buildMaestroFlowYaml', () => {
  it('emits the header, the separator and one command per step (inputText with an id taps the field first)', () => {
    const yaml = buildMaestroFlowYaml({ appId: APP, name: 'Login', tags: ['smoke'], steps: LOGIN });
    assert.equal(
      yaml,
      [
        `appId: ${APP}`,
        'name: "Login"',
        'tags:',
        '  - "smoke"',
        '---',
        '- launchApp:',
        '    clearState: true',
        '- tapOn:',
        `    id: "${ID}usernameTextField"`,
        '- inputText: "company"',
        '- hideKeyboard',
        '- tapOn:',
        `    id: "${ID}loginButton"`,
        '- assertVisible:',
        '    text: "Make Payment"',
        '- scrollUntilVisible:',
        '    element:',
        `      id: "${ID}logoutButton"`,
        '    direction: DOWN',
        '',
      ].join('\n')
    );
  });

  it('quotes awkward text safely', () => {
    const yaml = buildMaestroFlowYaml({ appId: APP, steps: [{ action: 'inputText', text: 'say "hi": #1' }] });
    assert.match(yaml, /- inputText: "say \\"hi\\": #1"/);
  });

  it('names the flow file from the flow name', () => {
    assert.equal(flowFileName('ExperiBank Login — smoke!'), 'experibank_login_smoke.yaml');
    assert.equal(flowFileName(undefined), 'flow.yaml');
  });
});

describe('validateMaestroFlow / bareIdWarnings', () => {
  it('reports every problem at once', () => {
    const errors = validateMaestroFlow({
      appId: 'not a package',
      steps: [{ action: 'tapOn' }, { action: 'inputText' }, { action: 'pressKey' }, { action: 'swipe' }, { action: 'assertVisible', id: 'a', text: 'b' }],
    });
    assert.equal(errors.length, 6, errors.join('\n'));
  });

  it('warns about a bare resource name (Maestro matches the whole resource-id)', () => {
    const w = bareIdWarnings({ appId: APP, steps: [{ action: 'tapOn', id: 'loginButton' }, { action: 'tapOn', id: `${ID}loginButton` }] });
    assert.equal(w.length, 1);
    assert.match(w[0], /com\.experitest\.ExperiBank:id\/loginButton/);
  });
});

describe('generate_maestro_flow tool', () => {
  let client: Client;
  let dir: string;
  beforeAll(async () => {
    resetClient('http://127.0.0.1:9', 'aut_1_maestro_test', 'maestro');
    const mcp = new McpServer({ name: 's', version: '0' });
    registerTestRunTools(mcp);
    client = new Client({ name: 'c', version: '0' });
    const [a, b] = InMemoryTransport.createLinkedPair();
    await Promise.all([mcp.connect(b), client.connect(a)]);
    dir = mkdtempSync(join(tmpdir(), 'maestro-'));
  });
  afterAll(() => rmSync(dir, { recursive: true, force: true }));

  const call = async (args: Record<string, unknown>) => {
    const res = (await client.callTool({ name: 'generate_maestro_flow', arguments: { appId: APP, steps: LOGIN, outputFormat: 'json', ...args } })) as { content: Array<{ text?: string }>; isError?: boolean };
    return { res, text: res.content.map((c) => c.text ?? '').join('') };
  };

  it('returns NO flow without a live inspection session or confirmSelectorsVerified', async () => {
    const { res, text } = await call({});
    assert.equal(res.isError, true);
    assert.equal(JSON.parse(text).reason, 'no_verified_selectors');
    assert.doesNotMatch(text, /appId: com/);
  });

  it('rejects placeholder selectors even when confirmed', async () => {
    const { res, text } = await call({ confirmSelectorsVerified: true, steps: [{ action: 'tapOn', id: '<resource-id from get_element_tree>' }] });
    assert.equal(res.isError, true);
    assert.match(text, /placeholder/);
  });

  it('writes a bundle the platform accepts (flows/<name>.yaml) and points at execute_test_run', async () => {
    const bundlePath = join(dir, 'login.zip');
    const { res, text } = await call({ confirmSelectorsVerified: true, flowName: 'Login', bundlePath });
    assert.notEqual(res.isError, true, text);
    const out = JSON.parse(text);
    assert.equal(out.flowFile, 'flows/login.yaml');
    assert.equal(checkMaestroBundle(bundlePath), null);
    assert.deepEqual(new AdmZip(bundlePath).getEntries().map((e) => e.entryName), ['flows/login.yaml']);
    assert.match(out.nextStep, /execute_test_run\(executionType: "MAESTRO", testsPath:/);
  });

  it('refuses a bundle path that is not a .zip', async () => {
    const { res, text } = await call({ confirmSelectorsVerified: true, bundlePath: join(dir, 'login.yaml') });
    assert.equal(res.isError, true);
    assert.match(text, /must end in \.zip/);
  });
});
